//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alembic.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alembic.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Id&quot;: &quot;1&quot;}.
        /// </summary>
        internal static string GetContainer_ReturnInvalidPayload {
            get {
                return ResourceManager.GetString("GetContainer_ReturnInvalidPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:&quot;4acb75f9185f058840a03037b223912c2b7ca05af8f7c5ba6fc3516765b990c7&quot;,&quot;Names&quot;:[&quot;/alembic&quot;],&quot;Image&quot;:&quot;mirzamerdovic/alembic:1.0.0&quot;,&quot;ImageID&quot;:&quot;sha256:4bc952a7ce156496fa02e77bc7384a849060b6ee3fb3f42c3e5e1ed5ab0a9cbb&quot;,&quot;Command&quot;:&quot;dotnet Alembic.dll&quot;,&quot;Created&quot;:1613225882,&quot;Ports&quot;:[],&quot;Labels&quot;:{&quot;com.docker.compose.config-hash&quot;:&quot;41f3b2713f90d12a428e05f78d9e8e34073219418067e8d983af5f647beb50be&quot;,&quot;com.docker.compose.container-number&quot;:&quot;1&quot;,&quot;com.docker.compose.oneoff&quot;:&quot;False&quot;,&quot;com.docker.compose.project&quot;:&quot;alembic&quot;,&quot;com. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetContainer_ReturnTwoContainers {
            get {
                return ResourceManager.GetString("GetContainer_ReturnTwoContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4acb75f9185f058840a03037b223912c2b7ca05af8f7c5ba6fc3516765b990c7.
        /// </summary>
        internal static string GetContainer_ReturnTwoContainers_ContainerId_1 {
            get {
                return ResourceManager.GetString("GetContainer_ReturnTwoContainers_ContainerId_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c842f638b2374a5993e7088f99023e9b0d0543b0aaeb82b137db302e49b4a112.
        /// </summary>
        internal static string GetContainer_ReturnTwoContainers_ContainerId_2 {
            get {
                return ResourceManager.GetString("GetContainer_ReturnTwoContainers_ContainerId_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Id&quot;:&quot;bbd92c776523bc5e8cfcd1ad8b52cb5f7f22421f59ea2659ac131f2c5ad140d0&quot;,&quot;Created&quot;:&quot;2021-02-11T21:41:35.2645907Z&quot;,&quot;Path&quot;:&quot;/opt/mssql/bin/sqlservr&quot;,&quot;Args&quot;:[],&quot;State&quot;:{&quot;Status&quot;:&quot;running&quot;,&quot;Running&quot;:true,&quot;Paused&quot;:false,&quot;Restarting&quot;:false,&quot;OOMKilled&quot;:false,&quot;Dead&quot;:false,&quot;Pid&quot;:31918,&quot;ExitCode&quot;:0,&quot;Error&quot;:&quot;&quot;,&quot;StartedAt&quot;:&quot;2021-02-11T21:41:35.8078915Z&quot;,&quot;FinishedAt&quot;:&quot;0001-01-01T00:00:00Z&quot;,&quot;Health&quot;:{&quot;Status&quot;:&quot;healthy&quot;,&quot;FailingStreak&quot;:0,&quot;Log&quot;:[{&quot;Start&quot;:&quot;2021-02-11T21:42:09.4376587Z&quot;,&quot;End&quot;:&quot;2021-02-11T21:42:09.5446493Z&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InspectContainer_ReturnHealthy {
            get {
                return ResourceManager.GetString("InspectContainer_ReturnHealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bbd92c776523bc5e8cfcd1ad8b52cb5f7f22421f59ea2659ac131f2c5ad140d0.
        /// </summary>
        internal static string InspectContainer_ReturnHealthy_Id {
            get {
                return ResourceManager.GetString("InspectContainer_ReturnHealthy_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Id&quot;:&quot;0051a16c5acf7a8b0615175111a805a244eeb01d19178ca30b006e715d420711&quot;,&quot;Created&quot;:&quot;2021-02-11T21:23:11.0504465Z&quot;,&quot;Path&quot;:&quot;docker-entrypoint.sh&quot;,&quot;Args&quot;:[&quot;sh&quot;,&quot;-c&quot;,&quot;mongod --bind_ip 0.0.0.0 --port 80&quot;],&quot;State&quot;:{&quot;Status&quot;:&quot;running&quot;,&quot;Running&quot;:true,&quot;Paused&quot;:false,&quot;Restarting&quot;:false,&quot;OOMKilled&quot;:false,&quot;Dead&quot;:false,&quot;Pid&quot;:25886,&quot;ExitCode&quot;:0,&quot;Error&quot;:&quot;&quot;,&quot;StartedAt&quot;:&quot;2021-02-11T21:36:46.897192Z&quot;,&quot;FinishedAt&quot;:&quot;2021-02-11T21:36:46.0908344Z&quot;,&quot;Health&quot;:{&quot;Status&quot;:&quot;starting&quot;,&quot;FailingStreak&quot;:2,&quot;Log&quot;:[{&quot;Start&quot;:&quot;2021-02-11T21:36: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InspectContainer_ReturnUnhealthy {
            get {
                return ResourceManager.GetString("InspectContainer_ReturnUnhealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0051a16c5acf7a8b0615175111a805a244eeb01d19178ca30b006e715d420711.
        /// </summary>
        internal static string InspectContainer_ReturnUnhealthy_Id {
            get {
                return ResourceManager.GetString("InspectContainer_ReturnUnhealthy_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;status&quot;:&quot;health_status: healthy&quot;,&quot;id&quot;:&quot;0051a16c5acf7a8b0615175111a805a244eeb01d19178ca30b006e715d420711&quot;,&quot;from&quot;:&quot;mongo:latest&quot;,&quot;Type&quot;:&quot;container&quot;,&quot;Action&quot;:&quot;health_status: unhealthy&quot;,&quot;Actor&quot;:{&quot;ID&quot;:&quot;0051a16c5acf7a8b0615175111a805a244eeb01d19178ca30b006e715d420711&quot;,&quot;Attributes&quot;:{&quot;autoheal&quot;:&quot;true&quot;,&quot;com.docker.compose.config-hash&quot;:&quot;3c6ff00d43678d363a09684bc59ea7345977ed77a247dab2a688740190fda366&quot;,&quot;com.docker.compose.container-number&quot;:&quot;2&quot;,&quot;com.docker.compose.oneoff&quot;:&quot;False&quot;,&quot;com.docker.compose.project&quot;:&quot;alembic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MonitorHealthStatus_Healthy {
            get {
                return ResourceManager.GetString("MonitorHealthStatus_Healthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;status&quot;:&quot;health_status: unhealthy&quot;,&quot;id&quot;:&quot;0051a16c5acf7a8b0615175111a805a244eeb01d19178ca30b006e715d420711&quot;,&quot;from&quot;:&quot;mongo:latest&quot;,&quot;Type&quot;:&quot;container&quot;,&quot;Action&quot;:&quot;health_status: unhealthy&quot;,&quot;Actor&quot;:{&quot;ID&quot;:&quot;0051a16c5acf7a8b0615175111a805a244eeb01d19178ca30b006e715d420711&quot;,&quot;Attributes&quot;:{&quot;autoheal&quot;:&quot;true&quot;,&quot;com.docker.compose.config-hash&quot;:&quot;3c6ff00d43678d363a09684bc59ea7345977ed77a247dab2a688740190fda366&quot;,&quot;com.docker.compose.container-number&quot;:&quot;2&quot;,&quot;com.docker.compose.oneoff&quot;:&quot;False&quot;,&quot;com.docker.compose.project&quot;:&quot;alemb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MonitorHealthStatus_Unhealthy {
            get {
                return ResourceManager.GetString("MonitorHealthStatus_Unhealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;status&quot;:&quot;health_status: unhealthy&quot;,&quot;id&quot;:&quot;0051a16c5acf7a8b0615175111a805a244eeb01d19178ca30b006e715d420711&quot;,&quot;from&quot;:&quot;mongo:latest&quot;,&quot;Type&quot;:&quot;container&quot;,&quot;Action&quot;:&quot;health_status: unhealthy&quot;,&quot;Actor&quot;:{&quot;ID&quot;:&quot;0051a16c5acf7a8b0615175111a805a244eeb01d19178ca30b006e715d420711&quot;,&quot;Attributes&quot;:{&quot;autoheal&quot;:&quot;true&quot;,&quot;com.docker.compose.config-hash&quot;:&quot;3c6ff00d43678d363a09684bc59ea7345977ed77a247dab2a688740190fda366&quot;,&quot;com.docker.compose.container-number&quot;:&quot;2&quot;,&quot;com.docker.compose.oneoff&quot;:&quot;False&quot;,&quot;com.docker.compose.project&quot;:&quot;alemb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MonitorHealthStatus_Unhealthy_ThreeTimes {
            get {
                return ResourceManager.GetString("MonitorHealthStatus_Unhealthy_ThreeTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pong.
        /// </summary>
        internal static string Ping_ReturnOk {
            get {
                return ResourceManager.GetString("Ping_ReturnOk", resourceCulture);
            }
        }
    }
}
