//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alembic.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alembic.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Id&quot;:&quot;bbd92c776523bc5e8cfcd1ad8b52cb5f7f22421f59ea2659ac131f2c5ad140d0&quot;,&quot;Created&quot;:&quot;2021-02-11T21:41:35.2645907Z&quot;,&quot;Path&quot;:&quot;/opt/mssql/bin/sqlservr&quot;,&quot;Args&quot;:[],&quot;State&quot;:{&quot;Status&quot;:&quot;running&quot;,&quot;Running&quot;:true,&quot;Paused&quot;:false,&quot;Restarting&quot;:false,&quot;OOMKilled&quot;:false,&quot;Dead&quot;:false,&quot;Pid&quot;:31918,&quot;ExitCode&quot;:0,&quot;Error&quot;:&quot;&quot;,&quot;StartedAt&quot;:&quot;2021-02-11T21:41:35.8078915Z&quot;,&quot;FinishedAt&quot;:&quot;0001-01-01T00:00:00Z&quot;,&quot;Health&quot;:{&quot;Status&quot;:&quot;healthy&quot;,&quot;FailingStreak&quot;:0,&quot;Log&quot;:[{&quot;Start&quot;:&quot;2021-02-11T21:42:09.4376587Z&quot;,&quot;End&quot;:&quot;2021-02-11T21:42:09.5446493Z&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Healthy_InspectContainer {
            get {
                return ResourceManager.GetString("Healthy_InspectContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bbd92c776523bc5e8cfcd1ad8b52cb5f7f22421f59ea2659ac131f2c5ad140d0.
        /// </summary>
        internal static string Healthy_InspectContainer_Id {
            get {
                return ResourceManager.GetString("Healthy_InspectContainer_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Id&quot;:&quot;0051a16c5acf7a8b0615175111a805a244eeb01d19178ca30b006e715d420711&quot;,&quot;Created&quot;:&quot;2021-02-11T21:23:11.0504465Z&quot;,&quot;Path&quot;:&quot;docker-entrypoint.sh&quot;,&quot;Args&quot;:[&quot;sh&quot;,&quot;-c&quot;,&quot;mongod --bind_ip 0.0.0.0 --port 80&quot;],&quot;State&quot;:{&quot;Status&quot;:&quot;running&quot;,&quot;Running&quot;:true,&quot;Paused&quot;:false,&quot;Restarting&quot;:false,&quot;OOMKilled&quot;:false,&quot;Dead&quot;:false,&quot;Pid&quot;:25886,&quot;ExitCode&quot;:0,&quot;Error&quot;:&quot;&quot;,&quot;StartedAt&quot;:&quot;2021-02-11T21:36:46.897192Z&quot;,&quot;FinishedAt&quot;:&quot;2021-02-11T21:36:46.0908344Z&quot;,&quot;Health&quot;:{&quot;Status&quot;:&quot;starting&quot;,&quot;FailingStreak&quot;:2,&quot;Log&quot;:[{&quot;Start&quot;:&quot;2021-02-11T21:36: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Unhealthy_InspectContainer {
            get {
                return ResourceManager.GetString("Unhealthy_InspectContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0051a16c5acf7a8b0615175111a805a244eeb01d19178ca30b006e715d420711.
        /// </summary>
        internal static string Unhealthy_InspectContainer_Id {
            get {
                return ResourceManager.GetString("Unhealthy_InspectContainer_Id", resourceCulture);
            }
        }
    }
}
